# Generated by Django 6.1 on 2026-08-29 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('VIEW', 'View'), ('CLICK', 'Click'), ('SEARCH', 'Search'), ('CART', 'Add to Cart'), ('PURCHASE', 'Purchase'), ('RATING', 'Rating')], max_length=20)),
                ('value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'product'], name='interaction_user_id_925641_idx'), models.Index(fields=['user', 'interaction_type'], name='interaction_user_id_237fd5_idx'), models.Index(fields=['product', 'interaction_type'], name='interaction_product_1114a0_idx')],
            },
        ),
    ]
